---
output:
  pdf_document: default
  html_document: default
---

# Abstract

**Background**: Prenatal maternal smoking has negative implications for child health.  DNA methylation signatures can function as biomarkers of prenatal smoke exposure. However the robustness of prenatal maternal smoking DNA methylation signatures across child ages, genetic ancestry groups or tissues is not clear. Using coefficients from a meta-analysis of prenatal maternal smoke exposure and DNA methylation in newborn cord blood, we created polymethylation scores of saliva DNA methylation from children at ages 9 and 15 in the Fragile Families and Child Wellbeing study.  We tested whether prenatal maternal smoking was associated with salivary polymethylation scores for prenatal smoke exposure and assessed the consistency of associations by age and participant genetic ancestry group. We tested the accuracy of exposure classification using area under the curve (AUC) from receiver operating curve analyses and compared to findings from candidate DNA methylation sites. 

**Results**: In the full sample at age 9 (n=`r table(modeldata$childteen)[1]`), prenatal maternal smoke exposure was associated with a `r coefCI(global_models, "childteen=='Age 9' & predictors=='base model' & str_detect(outcome, 'cell-type')", 'smkPreg_binaryYes', 2)` standard deviation higher polymethylation score. The direction and magnitude of the association was consistent in European and African genetic ancestry samples. In the full sample at age 15 (n=`r table(modeldata$childteen)[2]`), prenatal maternal smoke exposure was associated with a `r coefCI(global_models, "childteen=='Age 15' & predictors=='base model' & str_detect(outcome, 'cell-type')", 'smkPreg_binaryYes', 2)` standard deviation higher polymethylation score, and the association was attenuated among the European and Admixed - Latin genetic ancestry samples. The polymethylation score was reasonably accurate  at classifying prenatal maternal smoke exposure (AUC age 9=0.77, age 15=0.77). Including the polymethylation score increased the AUC of base model covariates by `r rct1%>%filter(childteen=='Age 9' & str_detect(modeltype, '6074'))%>%pull(6)` percentage points, while including a single candidate site in the *AHRR* gene did not (*P* val `r rct1%>%filter(childteen=='Age 9' & str_detect(modeltype, 'cg055'))%>%pull(7)%>%round(.,2)`). 
 
**Conclusions**: Prenatal maternal smoking was associated with DNA methylation signatures in child saliva samples, a clinically practical tissue. Polymethylation scores for prenatal maternal smoking were portable across genetic ancestries and more accurate than individual DNA methylation sites. DNA polymethylation scores from saliva samples could serve as robust and practical clinical biomarkers of prenatal maternal smoke exposure. 
