---
output:
  word_document: default
  html_document: default
bibliography: Methylation_SmokingBib.bib
---

# Background

Maternal prenatal smoking is a public health concern. In 2018, 11% of pregnant women in the United States aged 15-44 reported any past-month cigarette use [@SAMHSA2018]. Children exposed to cigarette smoking in utero are more likely to have low-birth weight, negative neurodevelopmental outcomes and asthma [@Banderali:2015vu]. Measuring prenatal maternal smoking behavior is challenging. Maternal prenatal smoking is underreported due to stigma [@Kvalvik:2012tk; @Dietz:2011ua]. The gold-standard for smoking measurements, serum cotinine levels, have a short half-life of nine hours in pregnant women [@Dempsey:2002wr]. Further, serum cotinine measures during pregnancy are rarely available outside of birth cohorts, limiting clinical application as a marker of prenatal exposures. Developing a portable and reliable biomarker of prenatal maternal smoke exposure would have important implications for research and clinical practice.

Maternal cigarette smoking during pregnancy is associated with reproducible DNA methylation signatures, measured in infant cord blood and placental tissues, and primarily tested in European cohorts [@Joubert:2016ue; @Everson:2021td; @Cardenas2019]. Prenatal maternal cigarette smoking exposure is associated with postnatal DNA methylation signatures in blood from cohorts of older children and adults[@Tehranifar:2018tb ; @Richmond:2018tu]. Few studies have considered the persistence of the association between maternal prenatal cigarette smoking and DNA methylation at different ages in the same individuals. Additionally, little work has considered the portability of the association between maternal prenatal cigarette smoking and DNA methylation across tissues and ancestry groups. DNA methylation drives cell differentiation and cell type proportions differ across tissue types. Epigenetic markers of prenatal maternal smoking are known to differ between cord blood and placental samples [@Everson:2021td]. Cord blood and placental samples are unlikely to be available in clinical settings. While peripheral blood is a more realistic clinical samples, saliva is even easier to collect. To our knowledge, no study has evaluated associations between maternal prenatal cigarette smoking and salivary DNA methylation. Additionally, DNA methylation can vary by genetics [@Galanter2017; @Fraser2012; @Moen2013; @Rahmani2017], and DNA methylation signatures of own-smoking differ across ancestry groups [@Barcelona2019; @Sun2013; @Philibert2013; @Philibert2012]. Only a few studies have examined associations between prenatal maternal cigarette smoking and DNA methylation in non-European ancestry populations. Among 954 infants, 70% of whom had mothers identifying as Black, prenatal maternal smoking was associated with cord blood DNA methylation at 38 CpG sites [@Xu2021]. The direction of these association between prenatal maternal cigarette smoking and DNA methylation at these sites were generally similar in children of Black and non-Black participants [@Xu2021]. Among 572 3-5 year old children, 186 of whom were of African or admixed ancestry, prenatal maternal smoking was associated with DNA methylation in peripheral blood samples but ancestry-stratified analyses were not performed [@Ladd-Acosta:2016aa]. Similarly, among 89 middle-aged women, of whom reported African American or Hispanic ethnicity, prenatal maternal cigarette smoking was associated with DNA methylation at 17 of 190 tested CpG sites [@Tehranifar:2018tb]. Adjusting for ancestry did not substantially affect the association between prenatal maternal smoking and DNA methylation at any of the sites, although the authors note that African American women had on average 2--5% higher mean DNA methylation on the absolute scale as compared with White and Hispanic women at 5 *CYP1A1* CpG sites [@Tehranifar:2018tb]. Of 148 CpG sites selected based on their association prenatal maternal smoking among primarily European children, 7 CpG sites were also associated with prenatal maternal cigarette smoking in a cohort of 572 Latino children [@Neophytou:2019ty; @Joubert:2016ue]. Thus, while prenatal maternal cigarette smoking is associated with DNA methylation, the consistency of this association across age, tissue and ancestry is understudied.

An important next step after association testing is the evaluation of DNA methylation as a biomarker of prenatal maternal smoke exposure, which is often done by comparing DNA methylation based classification of maternal smoking behavior to self-reported behavior. Many methods for constructing a DNA methylation biomarker exist, ranging in complexity from single CpG sites to machine learning algorithms such as support vector machines [@Philibert2020; @Philibert2013; @Reese:2017ts; @Richmond:2018tu; @Ladd-Acosta:2016aa]. One attractive option is a polymethylation score, analogous to a polygenic score. In a polymethylation score, CpG sites are weighted by the strength of their association with the variable of interest in a previous, independent sample and then summed to a single score [@Chen2020; @Bakulski2021a]. Using a subset of CpG sites selected with LASSO regression, one such DNA methylation score calculated from cord blood classified maternal smoking behavior with accuracy of 91% in a primarily European cohort [@Reese:2017ts]. Among 572 3-5 year old children, 186 of whom were of African or admixed ancestry, prenatal maternal smoking behavior could also be classified with an accuracy of 81% when using a support vector machine approach and DNA methylation at 26 sites measured in peripheral blood at a single time point [@Ladd-Acosta:2016aa]. Among middle-aged adults, a score calculated using DNA methylation in peripheral blood samples from a single time point could even predict prenatal smoke exposure (30 years previously) with an area under the curve of 0.72 (95% confidence interval 0.69, 0.76) [@Richmond:2018tu]. Ideally, a biomarker for prenatal maternal smoking would be consistent over participant age at methylation sampling and portable across genetic ancestry groups. However, the consistency of DNA methylation as a biomarker for prenatal maternal smoking across tissue, age and ancestry has not been evaluated. Few studies have compared the effectiveness of DNA methylation as biomarker of prenatal maternal smoking in the same individuals at different times or evaluated if the inclusion of multiple time points improves performance. No study has evaluated the accuracy of salivary DNA methylation as a biomarker for prenatal maternal smoking.

DNA methylation changes hold promise as a biomarker for prenatal maternal smoking. However, before translation to clinical applications, we must understand how and if the signal varies across age, ancestry and tissue sample. In the Fragile Families and Child Wellbeing study, a diverse longitudinal cohort of children, we aimed to assess the potential of salivary DNA methylation biomarkers for prenatal maternal cigarette smoking. We tested associations between prenatal maternal smoke exposure and saliva DNA methylation, including epigenetic clocks, polymethylation scores, and individual *a priori* CpG sites. We then performed age- and ancestry-stratified analyses to test the hypothesis that DNA methylation could serve as a persistent and portable biomarker of prenatal maternal smoking.
