---
output:
  word_document: 
    reference_docx: "../Template.docx"
  html_document: default
  pdf_document: default
bibliography: Methylation_SmokingBib.bib
always_allow_html: yes
---

```{r, echo=F, include=FALSE}
coefCI=function(df, filter_statement, my_term, si){
  my_df=df%>%
    filter(eval(parse(text = filter_statement)))%>%
    unnest(tidied)%>%
    mutate(val=paste0(round(estimate, si), ' (95%CI: ', 
                      round(conf.low, si), ', ',
                      round(conf.high, si), ')'))%>%
    filter(term==my_term)%>%
    pull(val)
  return(my_df)
}

coefOnly=function(df, filter_statement, my_term, si){
  df%>%
    filter(eval(parse(text = filter_statement)))%>%
    unnest(tidied)%>%
    mutate(val=round(estimate, si))%>%
    filter(term==my_term)%>%
    pull(val)
}

auc_ci=function(df, filter_statement){
  df=df %>%filter(eval(parse(text = filter_statement)))
  ci=paste0(round(df$auc, 2), ' (', 
            round(df$ci_auc_delong[[1]][1], 2), 
            ', ', 
            round(df$ci_auc_delong[[1]][3], 2)
            , ')')
  return(ci)
}

my_p_val=function(p){
  if(p<0.001){return_p='<0.001'}
  if(p>=0.001){return_p=paste0('=', round(p, 3))}
  return(return_p)
}
```

# Results

## Study sample descriptive statistics

Among selected participants in the Fragile Families and Child Wellbeing Study, saliva DNA methylation was measured on `r m_og_methyl` samples from `r n_og_methyl` unique child participants with the Illumina 450K array. Complete data on covariates of interest was available on `r m_obs` samples from `r n_total` participants who were included in the analysis (Figure 1). There were `r n_twovisit` participants with both age 9 and age 15 DNA methylation samples. Excluded participants were similar to included participants, except that included participants were slightly more likely to be of African genetic ancestry and less likely to be of Admixed Latin genetic ancestry (Supplemental Table 1). Among included participants, 20% percent of the mothers reported any prenatal maternal smoking, `r round(table(modeldata_wide$m1g2_YesNoPreg)/nrow(modeldata_wide)*100)['Yes']`% reported prenatal alcohol use and `r round(table(modeldata_wide$m1g3_YesNoPreg)/nrow(modeldata_wide)*100)['Yes']`% reported prenatal drug use. The mean income to poverty ratio of mothers at birth was `r round(mean(modeldata_wide$cm1inpov), 2)`. Of the included children, `r round(table(modeldata_wide$cm1bsex)/nrow(modeldata_wide)*100)['1 Boy']`% were male, `r round(table(modeldata_wide$ancestry)/nrow(modeldata_wide)*100)['African ancestry']`% were of African genetic ancestry, and `r round(table(modeldata_wide$ancestry)/nrow(modeldata_wide)*100)['Admixed ancestry - Latin heritage']`% were of Admixed Latin genetic ancestry.

 All of the polymethylation scores for prenatal smoke exposure were correlated with each other (Supplemental Figure 1). Our primary polymethylation score for prenatal smoke exposure, which was calculated using coefficients from a cell-type corrected regression, was weakly correlated with estimated cell-type proportion of immune cells (Pearson $r$=`r round(cor.test(modeldata$SSnewbornCT_center, modeldata$Leukocytes_saliva)$estimate, 2)`; *P* value `r my_p_val(cor.test(modeldata$SSnewbornCT_center, modeldata$Leukocytes_saliva)$p.value)`).

We compared epigenetic measures between the age 9 and age 15 visit among the `r n_twovisit` individuals with data from both visits (Supplemental Figure 2). The correlation across ages was strongest for the polymethylation scores for prenatal smoke exposure constructed using the Joubert meta-analysis coefficients from newborn cord blood (6074 site score with coefficients from regression with cell-type control Pearson $r$=`r round(cor(model_twovisit$SSnewbornCT_center_Age_9, model_twovisit$SSnewbornCT_center_Age_15), 2)`, *P* value\<0.0001; 568 site score $r$=`r round(cor(model_twovisit$richmond568_center_Age_9, model_twovisit$richmond568_center_Age_15), 2)`, *P* value\<0.0001). Global DNA methylation (`r round(cor(model_twovisit$globalmethylation_Age_9, model_twovisit$globalmethylation_Age_15), 2)`, *P* value\<0.0001) and epigenetic clocks were less strongly correlated across ages (Pediatric: `r round(cor(model_twovisit$PedBE_Age_9, model_twovisit$PedBE_Age_15), 2)`; *P* value\<0.0001, GRIM: `r round(cor(model_twovisit$DNAmGrimAge_Age_9, model_twovisit$DNAmGrimAge_Age_15), 2)`; *P* value\<0.0001) The distribution of epigenetic ages shifted higher between the age 9 and age 15 visit, as expected (Supplemental Figure 3).The distribution of estimated cell-type proportions also shifted between visits, while the distribution of global methylation and polymethylation scores were more consistent (Supplemental Figure 3). Almost all saliva samples consisted of mostly immune cells based on estimated cell-type proportions. At age 9, the mean estimated immune cell proportion was `r round(mean(modeldata_wide$Leukocytes_saliva_Age_9, na.rm=T), 2)` (range: `r paste(round(range(modeldata_wide$Leukocytes_saliva_Age_9, na.rm=T), 2), collapse=', ')`, 25% and 75% quantile: `r paste(round(quantile(modeldata_wide$Leukocytes_saliva_Age_9, c(0.25, 0.75), na.rm=T), 2), collapse = ', ')`). At age 15, the mean estimated immune cell proportion was `r round(mean(modeldata_wide$Leukocytes_saliva_Age_15, na.rm=T), 2)` (range: `r paste(round(range(modeldata_wide$Leukocytes_saliva_Age_15, na.rm=T), 2), collapse=', ')`, 25% & 75% quantile: `r paste(round(quantile(modeldata_wide$Leukocytes_saliva_Age_15, c(0.25, 0.75), na.rm=T), 2), collapse = ', ')`)


## Bivariate associations between prenatal maternal smoking and DNA methylation summary measures

Mothers who reported smoking during pregnancy had lower income to poverty ratios (mean=`r modeldata_people%>%filter(smkPreg_binary=='Yes')%>%summarise(mean(cm1inpov))%>%round(2)`) than those who did not (mean=`r modeldata_people%>%filter(smkPreg_binary=='No')%>%summarise(mean(cm1inpov))%>%round(2)`). Mothers who smoked were more likely to report prenatal alcohol use (`r with(modeldata_people, prop.table(table(smkPreg_binary, m1g2_YesNoPreg), margin=1))[2, 2]%>%round(2)*100`% vs `r with(modeldata_people, prop.table(table(smkPreg_binary, m1g2_YesNoPreg), margin=1))[1, 2]%>%round(2)*100`%), prenatal drug use (`r with(modeldata_people, prop.table(table(smkPreg_binary, m1g3_YesNoPreg), margin=1))[2, 2]%>%round(2)*100`% vs `r with(modeldata_people, prop.table(table(smkPreg_binary, m1g3_YesNoPreg), margin=1))[1, 2]%>%round(2)*100`%) and postnatal smoking (`r with(modeldata_people, prop.table(table(smkPreg_binary, PostnatalMaternalSmokingAny), margin=1))[2, 2]%>%round(2)*100`% vs `r with(modeldata_people, prop.table(table(smkPreg_binary, PostnatalMaternalSmokingAny), margin=1))[1, 2]%>%round(2)*100`%) than mothers who did not report prenatal maternal smoking (Table 1). Children of mothers who reported smoking during pregnancy were more likely to be of European genetic ancestry (`r round(with(modeldata_people, prop.table(table(smkPreg_binary, ancestry), margin=1))[2, 2], 2)*100`%) than children of mothers who did not (`r round(with(modeldata_people, prop.table(table(smkPreg_binary, ancestry), margin=1))[1, 2], 2)*100`%, *P* value=\<0.001). Children of mothers who reported smoking during pregnancy had higher prenatal maternal smoking polymethylation scores than children of mothers who did not at both age 9 (`r round(t.test(SSnewbornCT_center_Age_9~smkPreg_binary, data=modeldata_wide)$estimate['mean in group Yes'], 2)` vs `r round(t.test(SSnewbornCT_center_Age_9~smkPreg_binary, data=modeldata_wide)$estimate['mean in group No'], 2)`, *P* value\<0.001) and age 15 (`r round(t.test(SSnewbornCT_center_Age_15~smkPreg_binary, data=modeldata_wide)$estimate['mean in group Yes'], 2)` vs `r round(t.test(SSnewbornCT_center_Age_15~smkPreg_binary, data=modeldata_wide)$estimate['mean in group No'], 2)`, *P* value\<0.001) visits (Table 1, Supplemental Table 2). At age 9, children exposed to prenatal maternal smoking had lower DNA methylation at cg05575921 (`r round(t.test(cg05575921_Age_9~smkPreg_binary, data=modeldata_wide)$estimate['mean in group Yes'], 2)`%) than children of non-smoking mothers (`r round(t.test(cg05575921_Age_9~smkPreg_binary, data=modeldata_wide)$estimate['mean in group No'], 2)`%, *P* value=`r round(t.test(cg05575921_Age_9~smkPreg_binary, data=modeldata_wide)$p.value, 2)`). At age 15, children exposed to prenatal smoking had lower DNA methylation at cg05575921 (`r round(t.test(cg05575921_Age_15~smkPreg_binary, data=modeldata_wide)$estimate['mean in group Yes'], 2)`%) than children of non-smoking mothers (`r round(t.test(cg05575921_Age_15~smkPreg_binary, data=modeldata_wide)$estimate['mean in group No'], 2)`% *P* value= `r round(t.test(cg05575921_Age_15~smkPreg_binary, data=modeldata_wide)$p.value, 2)`). Epigenetic age from the pediatric and GRIM clocks and global DNA methylation did not differ between children exposed vs unexposed to prenatal maternal smoking (Figure 2).

## Multivariable associations between prenatal maternal smoking and DNA methylation summary measures

The association between prenatal maternal smoking and the polymethylation score for prenatal smoke exposure was also observed in multivariable models, adjusting for base model covariates of city indicator, child sex, maternal income to poverty ratio at baseline, proportion of salivary immune cells, sample plate from DNA methylation analysis, child age and the first two principal components of genetic ancestry (Figure 3; Supplemental Table 3). At age 9, prenatal maternal smoke exposure was associated with a `r coefCI(global_models, "childteen=='Age 9' & predictors=='base model' & str_detect(outcome, 'cell-type')", 'smkPreg_binaryYes', 2)` standard deviation higher polymethylation score for prenatal smoke exposure. At age 15, prenatal maternal smoke exposure was associated with a `r coefCI(global_models, "childteen=='Age 15' & predictors=='base model' & str_detect(outcome, 'cell-type')", 'smkPreg_binaryYes', 2)` standard deviation higher prenatal smoke exposure polymethylation score for prenatal smoke exposure.

A consistent association was observed when stratifying by genetic ancestry. In the African genetic ancestry sample (n= `r modeldata_people%>%filter(ancestry=='African ancestry')%>%nrow()`) at age 9, prenatal maternal smoking was associated with a `r coefCI(local_models, "childteen=='Age 9' & predictors=='base model' & str_detect(outcome, 'cell-type') & ancestry=='African ancestry'", 'smkPreg_binaryYes', 2)` standard deviation higher polymethylation score for prenatal smoke exposure. The effect was similar among European ancestry children at age 9 (`r coefCI(local_models, "childteen=='Age 9' & predictors=='base model' & str_detect(outcome, 'cell-type') & ancestry=='European ancestry'", 'smkPreg_binaryYes', 2)`) and consistent in direction but attenuated at age 15 (`r coefCI(local_models, "childteen=='Age 15' & predictors=='base model' & str_detect(outcome, 'cell-type') & ancestry=='European ancestry'", 'smkPreg_binaryYes', 2)`). The association was attenuated among Admixed - Latin ancestry children at ages 9 (`r coefCI(local_models, "childteen=='Age 9' & predictors=='base model' & str_detect(outcome, 'cell-type') & ancestry=='Admixed ancestry - Latin heritage'", 'smkPreg_binaryYes', 2)`) and 15 (`r coefCI(local_models, "childteen=='Age 15' & predictors=='base model' & str_detect(outcome, 'cell-type') & ancestry=='Admixed ancestry - Latin heritage'", 'smkPreg_binaryYes', 2)`) (Figure 3; Supplemental Table 3).

At age 9, prenatal maternal smoking was associated with `r -1*round(global_models %>% filter(childteen=='Age 9' & predictors=='base model' & outcome=='AHRR: cg05575921')%>%unnest(tidied)%>%filter(term=='smkPreg_binaryYes')%>%pull(estimate), 2)` percent lower DNA methylation at cg055975921 (95% CI: `r paste(round(global_models %>% filter(childteen=='Age 9' & predictors=='base model' & outcome=='AHRR: cg05575921')%>%unnest(tidied)%>%filter(term=='smkPreg_binaryYes')%>%pull(conf.low), 2), round(global_models %>% filter(childteen=='Age 9' & predictors=='base model' & outcome=='AHRR: cg05575921')%>%unnest(tidied)%>%filter(term=='smkPreg_binaryYes')%>%pull(conf.high), 2), sep=', ')`) after adjusting for base model covariates. Similarly, at age 15 prenatal maternal smoking was associated with `r -1*round(global_models %>% filter(childteen=='Age 15' & predictors=='base model' & outcome=='AHRR: cg05575921')%>%unnest(tidied)%>%filter(term=='smkPreg_binaryYes')%>%pull(estimate), 2)` percent lower DNA methylation at cg055975921 (95%CI: (`r paste(round(global_models %>% filter(childteen=='Age 15' & predictors=='base model' & outcome=='AHRR: cg05575921')%>%unnest(tidied)%>%filter(term=='smkPreg_binaryYes')%>%pull(conf.low), 2), round(global_models %>% filter(childteen=='Age 15' & predictors=='base model' & outcome=='AHRR: cg05575921')%>%unnest(tidied)%>%filter(term=='smkPreg_binaryYes')%>%pull(conf.high), 2), sep=', ')`)). Prenatal maternal smoking remained significantly associated with a decrease in cg05575921 DNA methylation in the African genetic ancestry sample at age 9 (`r coefCI(local_models, "childteen=='Age 9' & predictors=='base model' & outcome=='AHRR: cg05575921' & ancestry=='African ancestry'", 'smkPreg_binaryYes', 2)`) and age 15 (`r coefCI(local_models, "childteen=='Age 15' & predictors=='base model' & outcome=='AHRR: cg05575921' & ancestry=='African ancestry'", 'smkPreg_binaryYes', 2)`; Figure 3). In the European genetic ancestry sample, the association was consistent in direction at age 9 (`r coefCI(local_models, "childteen=='Age 9' & predictors=='base model' & outcome=='AHRR: cg05575921' & ancestry=='European ancestry'", 'smkPreg_binaryYes', 2)`) and age 15 (`r coefCI(local_models, "childteen=='Age 15' & predictors=='base model' & outcome=='AHRR: cg05575921' & ancestry=='European ancestry'", 'smkPreg_binaryYes', 2)`). In the Admixed Latin genetic ancestry sample, the association was no longer significant and not consistent in direction (Age 9: `r coefCI(local_models, "childteen=='Age 9' & predictors=='base model' & outcome=='AHRR: cg05575921' & ancestry=='Admixed ancestry - Latin heritage'", 'smkPreg_binaryYes', 2)`; Age 15: `r coefCI(local_models, "childteen=='Age 15' & predictors=='base model' & outcome=='AHRR: cg05575921' & ancestry=='Admixed ancestry - Latin heritage'", 'smkPreg_binaryYes', 2)`) (Figure 3).

Prenatal maternal smoking was not associated with global DNA methylation or epigenetic age (Figure 3).

## Sensitivity analysis: Specificity of DNA methylation signal to type and time of exposure

To assess the specificity of the DNA methylation signal to prenatal maternal cigarette smoking, we additionally adjusted for any other prenatal maternal drug use and prenatal maternal alcohol use. The association between prenatal maternal smoking and the polymethylation score was robust to this adjustment. The association between prenatal maternal smoking and cg05575921 was slightly attenuated (Supplemental Figure 4, Supplemental Table 2).

To assess the specificity of the DNA methylation signal to the timing of cigarette smoke exposure, we additionally adjusted for exposure to postnatal maternal smoking. Very few children exposed to maternal smoking prenatally were unexposed postnatally (Supplemental Figure 5). In bivariate analyses, children exposed to only postnatal smoking had lower polymethylation scores than those exposed to pre- and postnatal smoking. However, they did not have higher polymethylation scores than children unexposed to both pre-and postnatal smoking (Supplemental Figure 5). In multivariable analyses, prenatal maternal smoking was still associated with the polymethylation scores when adjusting for postnatal smoke exposure, though effect estimates were attenuated (Age 9: `r coefCI(global_models, "childteen=='Age 9' & predictors=='secondhand smoke exposure model' & str_detect(outcome, 'cell-type')", 'smkPreg_binaryYes', 2)` , Age 15: `r coefCI(global_models, "childteen=='Age 15' & predictors=='secondhand smoke exposure model' & str_detect(outcome, 'cell-type')", 'smkPreg_binaryYes', 2)`). Prenatal maternal smoking was no longer associated with cg05575921 methylation after adjusting for postnatal smoke exposure (Age 9: `r coefCI(global_models, "childteen=='Age 9' & predictors=='secondhand smoke exposure model' & outcome=='AHRR: cg05575921'", 'smkPreg_binaryYes', 2)`, Age 15: `r coefCI(global_models, "childteen=='Age 15' & predictors=='secondhand smoke exposure model' & outcome=='AHRR: cg05575921'", 'smkPreg_binaryYes', 2)`).

Effect estimates were also similar when controlling for surrogate variables instead of known covariates (Supplemental Figures 3 and 6; Supplemental Table 3).

## Sensitivity analysis: Choice of coefficients for constructing polymethylation score and associations with other *a priori* DNA methylation sites

Results were also similar when using sensitivity polymethylation scores (see Methods, Supplemental Figure 7) [@rauschert2020; @Richmond:2018tu].  

In addition to cg055975921 in the *AHHR* gene, we tested the association of four other *a priori* DNA methylation sites identified from previous meta-analyses. We replicated the association of prenatal maternal smoking with DNA methylation at GFI1: cg14179389, CYP1A1: cg05549655, MYO1G: cg22132788, and MYO1G: cg04180046  (Supplemental Figure 8).

## Polymethylation scores improve classification of prenatal smoke exposure while *AHRR*: cg05575921 alone does not

Next, we assessed whether including DNA methylation summary measures increased the accuracy of classifying prenatal smoke exposure over a base model consisting of child sex, maternal income to poverty ratio at baseline, child age at DNA methylation measurement, estimated immune cell proportion, plate from methylation processing, the first two genetic principal components and an indicator variable for oversampled city. At age 9, including the polymethylation score increased the AUC by `r rct1%>%filter(childteen=='Age 9' & str_detect(modeltype, '6074'))%>%pull(5)`) percentage points over the nested base model (*P* value from DeLong test=`r rct1%>%filter(childteen=='Age 9' & str_detect(modeltype, '6074'))%>%pull(7) %>%format(., scientific=F)`). At age 15 including the polymethylation score for prenatal smoke exposure increased the AUC by `r rct1%>%filter(childteen=='Age 9' & str_detect(modeltype, '6074'))%>%pull(5)` percentage points (*P* value from DeLong test=`r rct1%>%filter(childteen=='Age 9' & str_detect(modeltype, '6074'))%>%pull(7)%>%format(., scientific=F)`). Including DNA methylation at *AHRR*: cg0557591 with base model covariates did not improve the classification compared to using base model covariates alone  (Supplemental Tables 4 and 5).  Classification accuracy when including the polymethylation score from both age 9 and 15 was very similar to classification accuracy when using the polymethylation score from age 9 only (Figure 4B).

## Sensitivity analysis: Impact of choice of coefficients on polymethylation score accuracy and comparison to AUCs reported in the literature

The AUC for classification of prenatal maternal smoke exposure in the Fragile Families study was relatively similar regardless of which polymethylation score was used (Figure 5, Supplemental Table 5). The highest AUC was from the 568 site score using coefficients from the regression of prenatal smoke exposure and DNA methylation in newborn cord blood. Performance was similar to previous reports. Neither the 28-site score from a LASSO regression and the 204 site score from an elastic net regression performed as well in Fragile Families as has been reported previously in the literature (Figure 5). 


