---
output:
  word_document: 
    reference_docx: "../Template.docx"
  html_document: default
bibliography: Methylation_SmokingBib.bib
csl: springer-vancouver.csl
---

# Discussion

In the longitudinal Fragile Families and Child Wellbeing birth cohort, prenatal maternal smoking was associated with saliva DNA methylation in children at ages 9 and 15. Children with prenatal smoke exposure had `r coefCI(global_models, "childteen=='Age 9' & predictors=='base model' & str_detect(outcome, 'cell-type')", 'smkPreg_binaryYes', 2)` standard deviation higher polymethylation scores at age 9 than children not exposed. These findings were robust across strata of genetic ancestry and children's age. These signatures were specific, as global DNA methylation and epigenetic clocks were not associated with prenatal smoke exposure. When assessing biomarker utility, the polymethylation score for prenatal smoke exposure improved the classification of self-reported prenatal maternal smoking over a base model by `r rct1%>%filter(childteen=='Age 9' & str_detect(modeltype, 'polymethylation score'))%>%pull(5)` percentage points at age 9. A single *a priori* DNA methylation site, *AHRR*: cg05575921, did not ( `r rct1%>%filter(childteen=='Age 9' & str_detect(modeltype, 'cg05575921'))%>%pull(5)`percentage point increase). Our results suggest salivary DNA methylation can be used as an alternative to peripheral blood DNA methylation for biomarkers of prenatal maternal smoking. A saliva-based DNA methylation biomarker may be particularly useful in cases where blood collection, processing, and storage is not possible. Saliva can often be collected directly by participants and saliva sample collection kits have stabilizers allowing room temperature storage prior to DNA methylation measurement.

Our findings are consistent with the previous literature in different tissues and at different ages on associations between prenatal maternal smoking and DNA methylation. We replicated top hits from the seminal epigenome wide association meta-analysis of prenatal smoke exposure and DNA methylation of cord blood from newborns including *AHRR*: cg05575921, *GFl1*: cg14179389 and *MYO1G1*: cg22132788. Consistent with a meta-analysis of peripheral blood from children and adults over 16 years of age, the association at *MYO1G1*: cg22132788 was larger than in newborn cord blood [@Joubert:2016ue; @wiklund2019]. Again, consistent with a meta-analysis of peripheral blood from children and adults over 16 years of age, the associations at *AHRR*: cg05575921 and *GFl1*: cg14179389 were smaller than in newborn cord blood [@Joubert:2016ue; @wiklund2019]. There are no previous studies of prenatal maternal smoking and saliva DNA methylation. However, immune cell types are present in both blood and saliva, and saliva samples in our study were primarily composed of immune cells. Additionally, fewer than 4% of DNA methylation sites in blood and saliva samples displayed significantly different methylation values ($|\Delta \beta| >0.2$ and $p_{adj}< 0.001$) when measured on the 450K chip in samples of adults [@Langie2016] and 11-year old children [@Langie2017].

We also advance the prenatal smoking - DNA methylation literature by evaluating the generalizability of association between prenatal maternal smoking and DNA methylation across genetic ancestry groups. The portability of polygenic risk scores across genetic ancestries is a complex research area [@Martin2019] and evaluating the portability of epigenetic summary measures has been identified as a key area for evaluation [@Huls2020]. Our results suggest polymethylation scores for prenatal maternal smoking are portable across genetic ancestry groups. At age 9, the effect estimates for prenatal maternal smoking on the polymethylation score in the European and African genetic ancestry samples were within `r abs(coefOnly(local_models, "childteen=='Age 9' & predictors=='base model' & str_detect(outcome, 'cell-type') & ancestry=='European ancestry'", 'smkPreg_binaryYes', 2)-coefOnly(local_models, "childteen=='Age 9' & predictors=='base model' & str_detect(outcome, 'cell-type') & ancestry=='African ancestry'", 'smkPreg_binaryYes', 2))` standard deviation and were both significant at an alpha of 0.05. This finding is in line with a recent epigenome-wide association study in which children of both black and non-black identifying mothers exhibited similar directions of associations between prenatal smoke exposure and peripheral blood methylation at 38 DNA methylation sites [@Xu2021]. In our analysis, the association between prenatal smoke exposure and polymethylation scores was attenuated in children of admixed genetic ancestry (primarily of Hispanic ethnicity) at both ages and in children of European genetic ancestry at age 15. This could reflect differences in DNA methylation by genetic sequence at prenatal smoke sensitive DNA methylation sites [@Gonseth2016]. While genetic ancestry is distinct from racial and ethnic social and cultural constructs [@borrell2021], it can correlate with different social and environmental exposures. Differences in other social and environmental exposures could also contribute to the attenuation observed in the admixed genetic ancestry group.

We contribute to the understanding of the impact of tissue on classification accuracy of DNA methylation biomarkers for prenatal maternal smoking. Polymethylation scores using coefficients from the Joubert meta-analysis coefficients had similar AUCs in Fragile Families saliva samples (AUCs between `r roc_table%>%ungroup()%>%filter(str_detect(methylation, 'CT|568|19'))%>%dplyr::select(auc)%>%range()%>%round(., 2)%>%paste(. ,collapse=' and ')`) and in previous applications in peripheral blood samples from ages 17-, 30- and 31-years (AUCs between 0.69 and 0.72) [@Richmond:2018tu; @rauschert2020]. Thus, using polymethylation scores from saliva may be an acceptable alternative when peripheral blood samples are unavailable or difficult to obtain. However, other polymethylation scores for prenatal maternal smoking have performed better in peripheral blood samples. The greatest classification accuracy of prenatal smoke exposure from previous studies was with a 28-site LASSO regression score trained in and then applied to a Norwegian cord blood cohort (AUC=0.90) [@Reese:2017ts]. This score also accurately classified prenatal smoking from peripheral blood from adolescents and adults (AUCs between 0.85 and 0.73) [@rauschert2020]. A 204-site elastic net score trained and then applied to peripheral blood from 17-year-old's peripheral blood samples also performed very well (AUC=0.87) [@rauschert2020]. This score also performed well when applied to additional validation cohorts of peripheral blood from adolescents and adults (AUCs between 0.8 and 0.87). However, neither of these scores performed as well when applied in the Fragile Families cohort. The difference in classification accuracy could reflect cell proportion differences across tissues. Using coefficients from an epigenome-wide association analysis of saliva could improve classification and is a direction for future research.

While polymethylation scores significantly improved classification of prenatal smoke exposure over a base model, using *AHRR*: cg05575921 methylation as a classifier did not (percentage point increase in AUC: `r rct1%>%filter(childteen=='Age 9' & str_detect(modeltype, 'AHRR'))%>%pull(5)`)). Prenatal smoke exposed newborns consistently exhibit lower DNA methylation at *AHRR*: cg05575291 than unexposed newborns [@Joubert:2016ue]. However, the association between prenatal smoke exposure and *AHRR*: cg05575291 methylation did not persist in peripheral blood samples from adult women [@Richmond:2018tu]. Additionally, a previous longitudinal analysis of children's blood samples from birth to 17 years of age in the ALSPAC cohort found that the difference in DNA methylation at *AHRR*: cg05575291 between prenatal smoke exposed and unexposed children decreased from birth to 17 years of age. This previous analysis also reported that differences in DNA methylation at *AHRR*: cg05575291 in adolescence may be partially mediated by postnatal own smoking, and we excluded children who reported postnatal own-smoking [@Richmond:2018tu]. As the accuracy of *AHRR*: cg05575921 and other single CpG site biomarkers may be influenced by time-since-exposure and new environmental exposures, incorporating information across multiple sites of DNA methylation may yield a more robust biomarker.

Additionally, we found that prenatal maternal smoke exposure was not associated with global DNA methylation or a pediatric saliva and the GrimAge DNA methylation clocks, underlining the specificity of the DNA methylation signature of prenatal smoke exposure. DNA methylation clocks attempt to measure aspects of biological aging and are trained in specific populations. We note that the pediatric DNA methylation clock, which was specifically trained for use in pediatric populations, accurately recapitulated our subjects chronological ages. However, the GRIM age clock, which was trained in adults to measure proximity to mortality, overestimated chronological ages in our population by 10-15 years. In an analysis of four pediatric cohorts of children under 20 years of age, GRIM age estimates were 30-35 years greater than chronological in buccal cell samples and 10-15 years greater than chronological age in blood samples [@okazaki2021]. GRIM age was neither trained nor validated in a pediatric population [@lu2019], which may explain this overestimation.

Our analysis is not without its limitations. We used maternal self-report of prenatal maternal smoke exposure, as serum cotinine levels were not available. As mothers may be reluctant to report smoking during pregnancy, some of our children may be misclassified as unexposed to prenatal smoke. We would expect this to bias our results towards the null. Analyses of prenatal exposures and postnatal outcomes are conditioned on live birth and survival or enrollment until the point of outcome measurement. Because prenatal maternal smoking is associated with miscarriage [@pineles2014], this could result in selection bias if an unmeasured variable is associated with both live birth and the outcome. This selection bias can create a downward bias in the effect estimate. This could produce a spurious protective effect (which we did not observe), or, in the case of a true positive association between exposure and outcome, will attenuate the association toward the null [@leung2021; @liew2015]. Additionally, while we controlled for postnatal secondhand smoke exposure and excluded children who reported any own-smoking, we cannot exclude the possibility some of the observed effects are mediated through these alternative sources of smoke exposure. Personal smoking behavior among children in our cohort was relatively rare, and we excluded those participants from our analysis to focus on the prenatal exposure window. Future studies may focus on enriched risk samples to examine the joint effect of prenatal smoke exposure and personal smoking.

Our analysis is strengthened by our prospective study design, diverse study participants sampled, rigorous outcome measures, and advanced analytics. We analyzed samples from a large cohort of diverse participants, with African, Admix-Latin, and European genetic ancestry participants, including those who are currently underrepresented in genetic and epigenetic research [@Sirugo2019; @Bentley2017]. Our measurement of prenatal maternal smoke exposure was prospectively assessed at birth and preceded outcome measurements of DNA methylation measures, limiting the potential for recall bias. We analyzed repeated measures of DNA methylation with reproducible array measures conducted in a single batch, reducing the impacts of batch effects. We tested associations between prenatal maternal smoking and multiple DNA summary measures to evaluate the specificity of the polymethylation scores. To examine the specificity of the biomarker to the nature and timing of exposure, we adjusted for prenatal maternal drinking, other prenatal maternal drug use, and postnatal secondhand smoke exposure.
