# Conclusions

Our analysis contributes to the clinical implementation of a DNA methylation-based biomarker of prenatal maternal smoking. We showed that DNA methylation in saliva, a clinically practical tissue, had strong associations with and reasonable accuracy for prenatal maternal smoke exposure. Further, we demonstrated that polymethylation scores could be applied as a biomarker of prenatal maternal smoke exposure across ancestry-groups, an important consideration for health equity. The development and application of biomarker for prenatal maternal smoke exposure has important implications for epidemiological research and clinical practice. Given the difficulty of measuring prenatal maternal smoke exposure, such a biomarker could allow for confounder control in research areas where such control is currently impossible. Given the prevalence and negative health consequences of prenatal maternal smoke exposure, such a biomarker could be used to identify exposed individuals who might especially benefit from certain interventions.