---
output:
  word_document: 
    reference_docx: "../Template.docx"
  html_document: default
bibliography: [Methylation_SmokingBib.bib, packages.bib]
---

## Methods

### Cohort

The Fragile Families and Child Wellbeing Study is a birth cohort of nearly 5,000 children born in 20 cities in the United States between 1998 and 2000 [@Reichman:2001wv]. Participants were selected at delivery using a three-stage stratified random sample design which oversampled unmarried mothers by a ratio of 3:1 [@Reichman:2001wv]. Participants were excluded at the baseline wave on the following criteria: the parents who planned to place the child for adoption, the father was deceased, the parents did not speak English or Spanish well enough to be interviewed, the mother or baby were too ill to complete the interview, or the baby died before the interview could take place. Children were followed longitudinally with assessments at ages 1, 3, 5, 9, and 15; at age 22, follow up is ongoing. Across certain child ages, assessments included medical record extraction, biosample collection, in-home assessments, and surveys of the mother, father, primary caregiver, teacher, and child. At ages 9 and 15, a saliva sample was taken from the child [@Reichman:2001wv]. A subsample of the Fragile Families cohort was selected for saliva DNA and DNA methylation processing [@Reichman:2001wv]. To be eligible for the DNA methylation assessment, children had to have participated and given saliva at both ages 9 and 15, after which a random sample of these eligible participants was then selected. One exception to this, all participants from Detroit, Toledo, and Chicago (participants in the sub-Study of Adolescent Neurodevelopment (SAND) [@Gard2021]) were assayed for DNA methylation, even if they only provided a sample at one time-point. All analyses account for oversampling of these participants.

### Pre- and postnatal exposure measurement

At time of child's birth, mothers answered categorical questions about their pregnancy smoking, drug, and alcohol use. For maternal prenatal smoking, mothers were asked: "During your pregnancy, how many cigarettes did you smoke?". Responses were categorical: 2 or more packs a day, 1 or more but less than 2 packs per day, less than 1 pack a day, or none. Few participants reported smoking a pack or more a day. Thus, for our primary exposure variable, we created a dichotomous (any versus no prenatal smoke exposure) variable.

Mothers were also asked how frequently they drank during their pregnancy. We created a dichotomous any versus no prenatal alcohol exposure variable. Similarly, mothers were asked how frequently they used any other drug during their pregnancy. We again created a binary variable (any versus no prenatal use of other drugs).

When the children were 1, 5, 9, and 15 years of age, primary caregivers responded to questions about smoking in the household. To encapsulate early life postnatal secondhand smoke exposure, we created a binary variable for caregiver smoking behavior at ages 1 and/or 5 (any versus no). To encapsulate recent postnatal smoke exposure to the age 9 and 15 interview where DNA methylation was collected, we used a caregiver categorical variable for packs per day (no smoking, less than one pack/day, one or more packs/day) in the month prior to each interview.

At age 9 children were asked if they had ever smoked a cigarette or used tobacco (yes/no), and at age 15 they were asked if they had ever smoked an entire cigarette (yes/no).

### Covariate measurement

We used household income-to-poverty ratio at baseline as a proxy for socioeconomic status. Income-to-poverty ratio was the ratio of total household income (as self-reported by the mother) to the official poverty thresholds designated by the United States Census Bureau for the year preceding the interview.

Mothers reported sex (male/female) of their child at baseline.

Child genetic ancestry was calculated. Principal components (PC) of child genetic ancestry were calculated from genetic data measured using PsychChip (Illumina, San Diego, California) with child saliva samples [@FFPGS2021]. Genetic ancestry was assigned by comparing PC loadings to 1000 Genomes super population clusters. Samples with PC1 \> 0.018 and PC2 \> -0.0075 were assigned to European ancestry. Samples with PC1 \< -0.005 and PC2 \> 0.007+0.75(PC1) were assigned to African ancestry. Samples with PC1 \> 0.018 and -0.055 \< PC2 \< 0.025 were assigned to Admixed ancestry [@FFPGS2021]. Samples assigned to Admixed ancestry were primarily from individuals whose mothers self-reported Hispanic ethnicity (`r modeldata%>%group_by(ancestry, cm1ethrace)%>%summarise(n=n())%>%ungroup()%>%group_by(ancestry)%>%mutate(sum=sum(n), percent=round(100*(n/sum), 0))%>%filter(ancestry=='Admixed ancestry - Latin heritage' & cm1ethrace=='3 hispanic')%>%pull(percent)`% of samples), so we label this group Admixed - Latin ancestry.

### DNA methylation measurement

Salivary samples from the children were collected at ages 9 and 15 using the Oragene DNA sample collection kit (DNA Genotek Inc., Ontario). Saliva DNA was extracted manually using DNA Genotek's purification protocol using prepIT L2P. DNA was bisulfite treated and cleaned using the EZ DNA Methylation kit (Zymo Research, California). Age 9 and 15 samples were run on the same slide to minimize technical variation, and otherwise samples were randomized. Saliva DNA methylation was measured using the Illumina HumanMethylation 450k BeadArray [@Sandoval2011] and imaged using the Illumina iScan system. The bead arrays were processed at the Genome Sciences Core Facility at the Pennsylvania University College of Medicine (Hershey, PA).

DNA methylation image data were processed in R statistical software (4.1) using the Enmix package [@Xu2021a]. We used the February 2022 data freeze of the Fragile Families and Child Wellbeing DNA methylation data. The red and green image pairs (n=1,811) were read into R and the ENmix *preprocessENmix* and *rcp* functions were used to normalize dye bias, apply background correction and adjust for probe-type bias. Further quality control was applied using the ewastools packages [@Heiss2018]. We dropped samples using the following criteria: if \>10% of DNA methylation sites had detection p-value \>0.01 (n=`r prettyNum(probe_fail, big.mark=',')`), if there was sex discordance between DNA methylation predicted sex and recorded sex (n=`r sex_mismatch`), if samples had outlier methylation values (n=`r prettyNum(meth_outlier, big.mark=',')`) or if two sequential samples from the same individual exhibited genetic discordance between visits (n=`r prettyNum(genetic_discordance, big.mark=',')`) (Figure 1). Technical replicates were removed (n=`r tech_rep`). DNA methylation sites were removed if they had detection p-value \>0.01 in 5% of samples (n=33,376) [@Chen2013]. Relative proportions of immune and epithelial cell types were estimated from DNA methylation measures using a childhood saliva reference panel [@Middleton2021].

Our primary outcome variable was a polymethylation score for prenatal maternal smoke exposure. From an independent meta-analysis of prenatal smoke exposure and DNA methylation (the 2016 Joubert meta-analysis), we extracted the regression coefficients of 6,074 DNA methylation sites associated with prenatal maternal smoking at a false discovery ratio corrected $P$ value \<0.05 [@Joubert:2016ue]. For our main analysis we used coefficients from a regression of sustained smoking exposure and DNA methylation in newborn cord blood with cell-type control. We mean-centered the DNA methylation beta values in our study, weighted them by the independent regression coefficients, and took the sum across sites. This resulted in a single smoking polymethylation score per sample. To facilitate interpretation, we z-score standardized the polymethylation scores.

We investigated several sensitivity measures of DNA methylation, including several alternative polymethylation scores for smoke exposure, single DNA methylation sites, mean global DNA methylation, and DNA methylation clocks.

To assess the robustness of polymethylation scores to the source of coefficients for weights, we generated two sensitivity polymethylation scores from the 2016 Joubert meta-analysis [@Joubert:2016ue]. First, we used the regression of cord blood DNA methylation sites associated with prenatal maternal smoking at a strict Bonferroni threshold (n=569 sites), when analyses were not adjusted for cell proportions [@Joubert:2016ue]. Second, we used the regression coefficients of child peripheral blood DNA methylation sites associated with prenatal maternal smoking at the strict Bonferroni threshold (n=19 sites) when analyses were not adjusted for cell proportions [@Joubert:2016ue].

To assess the robustness of polymethylation scores to the source and selection of DNA methylation sites, we generated two additional sensitivity polymethylation scores. One score was generated using DNA methylation sites and coefficients prioritized from a LASSO regression of prenatal maternal smoking and cord blood methylation in the Norwegian Mother and Child Cohort Study (n=28 sites) [@Reese:2017ts]. Another score was generated using DNA methylation sites and coefficients prioritized from an elastic net regression of prenatal maternal smoking and DNA methylation in adolescent peripheral blood (n=204 sites) [@rauschert2020]. This score was calculated using the coefficients and code provided by the authors in the R code accompanying the manuscript [@R-DNAsmokeR].

To compare the utility of polymethylation scores relative to single site biomarkers, we selected the top DNA methylation site from the 2016 Joubert meta-analysis, *AHRR:* cg05575921. As a sensitivity analyses, we also selected four other *a priori* DNA methylation sites which were identified from meta-analyses of prenatal maternal smoking and DNA methylation in children's cord and peripheral blood samples: *GFI1*: cg14179389, *CYP1A1*: cg05549655, *MYO1G*: cg22132788, and *MYO1G*: cg04180046 [@Joubert:2016ue; @wiklund2019].

To assess the specificity of the impact of prenatal smoke exposure on DNA methylation, we compared the polymethylation scores to mean global and regulatory regional DNA methylation and DNA methylation-derived age measures. Global DNA methylation was calculated for each sample as the mean methylation value of each sample across the pre-processed array. Mean DNA methylation for each genomic regions (CpG island, shore, shelf or open sea, as identified in the R package IlluminaHumanMethylation450kanno.ilmn12.hg19 v 0.6.0) was also calculated. Pediatric epigenetic age was calculated for each sample using the coefficients and methods provided by the creators (see [\<https://github.com/kobor-lab/Public-Scripts\>](https://github.com/kobor-lab/Public-Scripts){.uri}) [@mcewen2019]. As a sensitivity analysis, the GRIM-age clock, which was neither trained nor validated in a pediatric population, was calculated as previously described [@lu2019].

To control for unmeasured confounding and potential batch effects, we calculated surrogate variables from DNA methylation data using the function sva from the R package sva version 3.38 [@R-sva]. The relationship between prenatal maternal smoking and DNA methylation was protected.

### Statistical analyses

#### Inclusion exclusion criteria

Among samples with pre-processed DNA methylation values, we excluded samples missing any data on the following variables: maternal prenatal smoking, maternal prenatal alcohol use, maternal prenatal other drug use, maternal income to poverty ratio, postnatal secondhand smoke exposure variables, child sex, or child age. We also excluded samples that were missing genetic data. To ensure we measured the direct effect of prenatal exposure to cigarette smoke, rather than the effect of personal postnatal smoking, we also excluded children who reported own smoking. Specifically, samples from children who reported ever smoking a cigarette or using tobacco at age 9 or were missing own-smoking data were excluded. Samples from children who reported smoking a cigarette at age 9 or at age 15 or were missing own-smoking data were excluded. Children who were missing a response to the question at age 9 but answered that they had never smoked a whole cigarette at age 15 were kept in the sample. Sample inclusion was visualized using a flow chart.

#### Descriptive statistics

We described the distribution of continuous variables using the mean and standard deviation. We described the distribution of categorical variables using frequencies. We compared the distribution of included to excluded samples using the Welch's t-test for continuous variables and the Chi-Square test for categorical variables. We reported the correlation between continuous measures of DNA methylation (including polymethylation scores, single sites, mean global DNA methylation and estimated cell type proportions) using pairwise Pearson correlation coefficients. We reported the correlation of these DNA methylation measures between visits using pairwise Pearson correlation coefficients and scatter plots. We compared the distribution of variables by exposure status to prenatal maternal smoking using the Welch's t-test for continuous variables and the Chi-Square test for categorical variables. For select continuous DNA methylation measures we compared the distributions across prenatal smoke exposure status using violin plots with captive box plots.

#### Regression analyses

To assess the association between our primary exposure variable (prenatal maternal smoking) and primary outcome variable (salivary DNA methylation polymethylation score), we performed age-stratified, multivariable linear regressions. We adjusted for an indicator variable for maternal residence in one of the oversampled cities (Chicago, Detroit, or Toledo), maternal income to poverty ratio at baseline, child sex, child age, plate from DNA methylation processing, estimated immune cell proportion from DNA methylation data, and the first two components of genetic ancestry from principal component analysis. While child sex, child age, plate from DNA methylation processing, and immune cell proportions are not confounders (as they cannot causally effect prenatal maternal smoke exposure), these variables can strongly effect DNA methylation and so were adjusted for as precision variables. We reported the effect estimate for polymethylation score term and the 95% confidence interval (CI). We visualized our findings using forest plots.

To assess the portability of the association between our primary exposure variable of prenatal maternal smoking and salivary DNA methylation across genetic ancestry, we additionally stratified by genetic ancestry and reran the models described above. In ancestry-stratified models, the first two principal components from principal component analysis run within each ancestry strata were used.

To compare the utility of the polymethylation score to a single site biomarker, we used percent methylation at AHRR: cg05575921 as the outcome in the models described above. To assess the specificity of the impact of prenatal maternal smoking on DNA methylation, we used mean percent global DNA methylation and the pediatric DNA methylation clock as outcome variables.

#### Regression sensitivity analyses

To assess the specificity of the DNA methylation signal to the type and timing of exposure, we additionally adjusted for the following variables in sensitivity analyses: 1) prenatal drug and alcohol use and 2) postnatal second-hand smoke exposure in addition to prenatal drug and alcohol use. To assess the robustness of the association between prenatal maternal smoking and DNA methylation to batch effects and residual confounding, we also performed regression analyses adjusting for surrogate variables calculated from the DNA methylation data.

To assess the robustness of the association to the choice of polymethylation score, we performed the same regression analyses described above with sensitivity polymethylation scores as the outcome. Similarly, we replaced the outcome variable of *AHRR:* cg05575921 with other *a priori* selected DNA methylation sites in sensitivity analyses. We plotted the estimates and 95% CI for each DNA methylation site along with the previously reported estimates from the literature using forest plots [@Joubert:2016ue; @wiklund2019]

#### Receiver operator curve analysis

To evaluate the accuracy of the DNA methylation summary measures as biomarkers of prenatal maternal smoking, we used a receiver operating curve [@robin2011]. First, we regressed exposure to prenatal maternal smoking (outcome) against the DNA methylation summary measures in individual logistic regressions, while adjusting for the base model variables from regression analyses. The base model variables included indicator variable for maternal residence in one of the oversampled cities (Chicago, Detroit or Toledo), maternal income to poverty ratio at baseline, child sex, child age, plate from DNA methylation processing, estimated immune cell proportion from DNA methylation data, and the first two components of genetic ancestry from principal component analysis. Next, we calculated receiver operating curves (ROC) and area under the curves (AUCs) using the function *roc* from the R library pROC version 1.18.0 [@pROC2011]. We compared ROC curves and AUCs from models with only base model variables to those which included base model variables and the methylation summary measure using the Delong method and the function *roc.test* from the pROC library. This is appropriate as the base model is nested within the base model variable + methylation summary measures model.

#### Receiver operator curve sensitivity analyses

To assess the robustness of polymethylation scores classification accuracy to the choice of polymethylation score coefficients, we used polymethylation scores calculated using different coefficient sets as predictors for the receiver operating curve analysis in sensitivity analyses.

To compare the performance of saliva-based polymethylation scores to previous reports of blood-based polymethylation scores, we used a forest plot. We plotted the AUC and 95% CI (when available) for each polymethylation score in our cohort and in the cohorts previously reported in the literature [@rauschert2020; @Richmond:2018tu].
