# Declarations

### Ethics approval and consent to participate

Participants provided written informed consent for the study. The data used in this manuscript were prepared by the Fragile Families and Childhood Wellbeing Study administrators following approval of the manuscript proposal. These secondary data analyses were approved by the University of Michigan Institutional Review Board (IRB, HUM00129826) 

### Consent for publication

Not applicable

### Availability of data and materials

Code to perform all analyses is available (www.github.com/bakulskilab). Survey data for the Fragile Families and Child Wellbeing study are publicly available (https://fragilefamilies.princeton.edu/documentation). DNA methylation and genetic data in the Fragile Families and Child Wellbeing study are available through the Restricted Use Contract (https://fragilefamilies.princeton.edu/restricted), upon demonstrated Institutional Review Board approval of the proposed research and data protection plan. 

### Competing interests

The authors have no competing interests to declare.

### Funding

This research was made possible through several grants (Fragile Families Core Data Collection: R01 HD036916, genetic data processing R01 HD36916, R01 HD073352, R01 MD011716, and R01 HD076592). FB was supported by the National Institutes of Health National Institute of Dental and Craniofacial Research (F31 DE029992) and R25 AG053227. KB was supported by R01 AG074887 and R01 MD013299. EB was supported by R01 AG055406, R01 AG067592, and R01 MD011716. LS, DN, and JF were supported by R01 HD076592, R01 MD011716. CM was supported by R01 AG07107, R01 MD011716, R01 HD076592.

### Authors' contributions

FB performed the analysis with contributions from JD, JF, and EW. FB and KB wrote the paper with all authors contributing to revisions. CM, DN and LS contributed to the design and processing of the DNA methylation data subcohort. DN, CM, KM, EW, and FB all contributed to the design and conception of the analytic plan.  All authors reviewed and revised the manuscript.

### Acknowledgements

Not applicable 
